import type { Metadata } from 'next';
// import localFont from 'next/font/local';
import { Inter } from 'next/font/google';
import './globals.css';
import { RecoilRoot } from 'recoil'; // Import RecoilRoot
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRoot> {/* Wrap the entire application in RecoilRoot */}
          <Providers>
            {children}
          </Providers>
        </RecoilRoot>
      </body>
    </html>
  );
}
